### ISSUE TITLE
Fly

### ISSUE THREAD

**Issue by QuiverlyRivalry** [DaPigGuy/PiggyAntiCheats#6]
Hi Piggy :D 
I found. A bug on this plugin, or not sure it's just two plugins conflicting, but when I took Piggy anti cheat put it started to work again The fly anti cheat won't let you fly on gmc does it think ops are hacking?

**Comment by optimusprime338** [comment]
same for me

**Comment by DaPigGuy** [comment]
Huh

**Comment by optimusprime338** [comment]
It's not letting you fly even if u are using /fly command or you are in creative mode!!!

**Comment by DaPigGuy** [comment]
Try now
